### PR TITLE
Remove BB dependency from amorphic frontend client code

### PR DESCRIPTION
**Pull request by zamn**
Currently amorphic frontend code has a direct dependency on Bluebird which means any repository wanting to use amorphic must also use Bluebird. The intent of this PR is to remove that direct dependency.

### CODE REVIEW

**Comment by sshankar19** [comment]
Please add an entry to the History.md for amorphic and also bump the version to a minor version upgrade in amorphic

**Review by sshankar19 — CHANGES_REQUESTED** [review]
Please add an entry to the History.md for amorphic and also bump the version to a minor version upgrade in amorphic

**Comment by zamn** [comment]
@sshankar19 thanks for the quick response! Can you also let me know what test is broken? It passes locally so I'm not sure what to fix :thinking:

**Comment by sshankar19** [comment]
> @sshankar19 thanks for the quick response! Can you also let me know what test is broken? It passes locally so I'm not sure what to fix 🤔

@zamN That's an issue with the images circle ci pulls for postgres. I have a feeling it's messign up with our pipelines. Don't worry about that for the time being, as long as there are only 2 tests failing and they are both delete tests, 1 for mongo and 1 for knex, then it's okay for the time being

**Review by sshankar19 — DISMISSED** [review]

**Review by nsaenz7 — DISMISSED** [review]

**Review by nsaenz7 — APPROVED** [review]

**Review by sshankar19 — APPROVED** [review]

**Pull request merged**
